### ISSUE TITLE
rpackage dependencies and early exit

### ISSUE THREAD

**Issue by iwccsbfb** [muxspace/crant#28]
if I run 
`rpackage -r http://cloud.r-project.org/ igraph reshape2`
`igraph` depend on `reshape2`, so it will first install `reshape2`. 
Then it starts to deal with `reshape2`, and it will install `reshape2` again. 

A better way might be: finding the dependencies of all packages first, do a topological sort to the dependency graph, the install packages from the first to the end. 

Also, if we want to install several packages (similar as the above example), and the first package installation fails, then the program will continue to install next package.
It might be better for an early exit. 

If we do a topological sort on the dependency graph, and find any package that cannot be installed, we just exit the program and don't continue.

**Comment by muxspace** [comment]
Do you have an approach to do this simply?

**Comment by iwccsbfb** [comment]
I just tested the same command, did not see this problem to occur again
